pdBase=http://localhost:9091/
vdBase=http://localhost:9090/
;controllerAddr=http://localhost:9081/services/FGService
;vdAddress=http://localhost:9080/services/VDService
;datDirAdress=http://localhost:9081/services/DDService
;pdAddress=http://localhost:9081/services/PDService
;pdCallbackAddress=http://localhost:9081/services/PDCallback
